import { Permission, PERMISSIONS } from "./permissions";
import { ROLES, UserRole } from "./roles";

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.WORKITEMS_VIEW,
    PERMISSIONS.WORKITEMS_CREATE,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.WORKITEMS_VIEW,
    PERMISSIONS.WORKITEMS_CREATE,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
  ],

  [ROLES.CONTRIBUTOR]: [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.WORKITEMS_VIEW,
  PERMISSIONS.PROFILE_VIEW,
  PERMISSIONS.SETTINGS_VIEW,
  ],
};